---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Chart.Name }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.type }}
